on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/f8f4388ce6dcf662450635f2fa6bae0c
          gist_title: Pr치ctica 6 - ADC Set Point MPLAB X PIC assembler PIC18F4550
          gist_description: Pr치cticas PIC Assembler
          github_file: Proyecto/PIC18F4550/ADC_set_point.X/adc_set_point.s
          file_encoding: ISO-8859-1
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/441a3b6ff7ab1d6ded36d592eed67a19
          gist_title: Pr치ctica 6 - ADC Set Point MPLAB X PIC assembler PIC18F45K50
          gist_description: Pr치cticas PIC Assembler
          github_file: Proyecto/PIC18F45K50/ADC_set_point.X/adc_set_point.s
          file_encoding: ISO-8859-1